sonar.projectKey=ravisin236-arch_secure-devops-backend
sonar.organization=ravisin236-arch
sonar.sources=.
sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.pyc,uploads/**
sonar.sourceEncoding=UTF-8
